server:
  port: 8080
  
# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode: false
  
# Workaround for https://github.com/vaadin/flow/issues/5947
spring:
#  devtools:
#    restart:
#      additional-exclude: META-INF/VAADIN/config/**
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-name: Test
            client-id: nJotFHgcNpf84y32ifFnpgiuSnxBYA9y
            client-secret: 4o1z2Qd8B7HApC67R7_efpeuLguNzc8vHm4706QRxN5lzK9jc43JyYkfMZ4LWGZj
            scope:
              - openid
              - profile
              - email
              - offline_access
            authorization-grant-type: authorization_code
        provider:
          auth0:
            issuer-uri: https://dev-vt4d68dy.eu.auth0.com/
            user-name-attribute: name


